/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

// Import the functions you need from the SDKs you need
// import { initializeApp } from "firebase/app";
// // // TODO: Add SDKs for Firebase products that you want to use
// // // https://firebase.google.com/docs/web/setup#available-libraries
// import { getMessaging } from "firebase/messaging";
// import { onBackgroundMessage } from "firebase/messaging/sw";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith("/_")) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html"),
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) =>
    (url.origin === self.location.origin ||
      url.origin === "cdn.weatherapi.com") &&
    url.pathname.endsWith(".png"), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: "images",
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  }),
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.

// Caching for google fonts
const CURRENT_CACHES = {
  font: "google-font-cache-v3",
};

self.addEventListener("fetch", (event) => {
  event.respondWith(handleRequest(event));
});

async function handleRequest(event) {
  // Break out if request does not match
  if (
    (event.request.cache === "only-if-cached" &&
      event.request.mode !== "same-origin") ||
    event.request.url.indexOf("https://fonts.googleapis.com/css") !== 0
  ) {
    return await fetch(event.request);
  }

  const request = new Request(
    // Rewrite Request Object
    event.request.url,
    {
      method: event.request.method,
      body: event.request.body,
      mode: "cors",
      credentials: "omit",
      cache: event.request.cache,
      redirect: event.request.redirect,
      referrer: event.request.referrer,
      integrity: event.request.integrity,
    },
  );

  const response = await fetch(request);
  if (response.status < 400) {
    const cache = await caches.open(CURRENT_CACHES.font);
    const cacheResponse = await cache.match(event.request);
    if (cacheResponse) {
      return cacheResponse;
    }
    const css = await response.text();
    // Patch CSS to Include "font-display: swap"
    const patched = css.replace(/}/g, "  font-display: swap; \n}");
    const newResponse = new Response(patched, { headers: response.headers });
    cache.put(event.request, newResponse.clone());
    return newResponse;
  }
  return response;
}

// Your web app's Firebase configuration
/* global firebase */
/* global importScripts */

importScripts(
  "https://www.gstatic.com/firebasejs/9.22.1/firebase-app-compat.js",
);
importScripts(
  "https://www.gstatic.com/firebasejs/9.22.1/firebase-messaging-compat.js",
);

const firebaseConfig = {
  apiKey: "AIzaSyDfdNUWbr3d5XBVIHJ47QGDS1GI_w5E5JQ",
  authDomain: "wgu-summit.firebaseapp.com",
  projectId: "wgu-summit",
  storageBucket: "wgu-summit.appspot.com",
  messagingSenderId: "443766700141",
  appId: "1:443766700141:web:bd2a2552af6e3485e52764",
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
  console.log("[Service Worker] Received background message ", payload);
  const notificationTitle = payload.notification.title;
  const notificationOptions = {
    body: payload.notification.body,
    icon: payload.notification.icon || "/favicon.svg",
    // Add other options if needed
  };

  self.registration.showNotification(notificationTitle, notificationOptions);
});
